version: 2

models:
  - name: clickstream_full
    description: All rows from the clickstream data. This is a ephemeral table to easily reference it where needed.

    columns:
        - name: date_time
          description: Date time formatted column. Used for time parting.
          tests:
              - not_null
  
  - name: clickstream_clean
    description: Only hits that are included in Adobe Analytics reports are included.
    
  - name: clickstream_discarded
    description: Excluded hits from the Adobe Analytics reports. Stored for debugging purposes.

  - name: daily_visits
    description: Daily visits.

  - name: daily_page_views
    description: Daily page views.
        